services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: ./configs/config.env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis_rdb:
    image: redis:latest
    container_name: redis_rdb
    command: redis-server --save 5 1 --appendonly no
    ports:
      - "6379:6379"
    volumes:
      - redis_rdb_data:/data

  redis_aof:
    image: redis:latest
    container_name: redis_aof
    command: redis-server --save "" --appendonly yes --appendfsync everysec # always 
    ports:
      - "6380:6379"
    volumes:
      - redis_aof_data:/data

  influxdb:
    image: influxdb:1.11-alpine
    platform: linux/amd64
    env_file: ./configs/config.env
    ports:
      - '127.0.0.1:8086:8086'
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb
    restart: unless-stopped

  telegraf:
    image: telegraf:1.33.0
    platform: linux/amd64
    volumes:
      - ./configs/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
      - rabbitmq
      - redis_rdb
      - redis_aof
    links:
      - influxdb
    environment:
      - HOSTNAME=telegraf 
    ports:
      - '127.0.0.1:8125:8125/udp'
    restart: unless-stopped 

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  rabbitmq_data:
  redis_rdb_data:
  redis_aof_data:
  influxdb_data:
  grafana_data:
