version: "3.8"

services:
  nginx:
    image: anroe/nginx-geoip2
    container_name: load_balancer
    platform: linux/amd64
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./geoip:/etc/nginx/geoip
    ports:
      - "80:80"
    depends_on:
      - server1
      - server2
      - server3
      - server4
      - backup_server

  server1:
    image: nginxdemos/hello
    container_name: uk_server
    environment:
      - SERVER_NAME=Server 1 (UK)
    restart: always

  server2:
    image: nginxdemos/hello
    container_name: us_server_1
    environment:
      - SERVER_NAME=Server 2 (US)
    restart: always

  server3:
    image: nginxdemos/hello
    container_name: us_server_2
    environment:
      - SERVER_NAME=Server 3 (US)
    restart: always

  server4:
    image: nginxdemos/hello
    container_name: world_server
    environment:
      - SERVER_NAME=Server 4 (World)
    restart: always

  backup_server:
    image: nginxdemos/hello
    container_name: backup_server
    environment:
      - SERVER_NAME=Backup Server
    restart: always