services:
  attacker:
    image: utkudarilmaz/hping3
    platform: linux/amd64
    container_name: attacker
    entrypoint: "/bin/sh -c 'sleep infinity'"

  nginx_insecure:
    image: nginx:latest
    container_name: nginx_insecure
    volumes:
      - ./nginx_insecure.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"

  nginx_secure:
    image: nginx:latest
    container_name: nginx_secure
    volumes:
      - ./nginx_secure.conf:/etc/nginx/nginx.conf
    ports:
      - "8081:80"

  influxdb:
    image: influxdb:1.11-alpine
    platform: linux/amd64
    container_name: influxdb
    ports:
      - '8086:8086'
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
    volumes:
      - ./:/imports
      - influxdb_data:/var/lib/influxdb 

  telegraf:
    image: telegraf:1.33.0
    platform: linux/amd64
    container_name: telegraf
    volumes:
      - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    links:
      - influxdb
    environment:
      - HOSTNAME=telegraf 
    ports:
      - '127.0.0.1:8125:8125/udp'
    restart: unless-stopped 

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin    
      - GF_SECURITY_ADMIN_PASSWORD=admin 
      - GF_AUTH_ANONYMOUS_ENABLED=true   
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin  
      - GF_USERS_ALLOW_SIGN_UP=true
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb

volumes:
  influxdb_data:
  grafana_data: