services:
  postgres:
    image: postgres:15
    container_name: postgresql-b
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  postgres_shard1:
    image: postgres:15
    container_name: postgresql-b1
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books_1
    ports:
      - "5433:5432"
    volumes:
      - postgres_shard1_data:/var/lib/postgresql/data

  postgres_shard2:
    image: postgres:15
    container_name: postgresql-b2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: books_2
    ports:
      - "5434:5432"
    volumes:
      - postgres_shard2_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  postgres_shard1_data:
  postgres_shard2_data: