fdw:
	docker-compose -f docker-compose.fdw.yaml down -v && docker-compose -f docker-compose.fdw.yaml up -d

citus:
	docker-compose -f docker-compose.citus.yaml down -v && docker-compose -f docker-compose.citus.yaml up -d