global:
  scrape_interval: 1s
  evaluation_interval: 1s # TODO: check for every 500ms

scrape_configs:
  - job_name: "redis-exporter"
    static_configs:
      - targets: ["redis-exporter:9121"]

  - job_name: "redis-cluster"
    metrics_path: /scrape
    static_configs:
      - targets:
          - redis-node-1:6379
          - redis-node-2:6380
          - redis-node-3:6381
          - redis-node-4:6382
          - redis-node-5:6383
          - redis-node-6:6384
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis-exporter:9121
