services:
  bind9:
    image: ubuntu/bind9
    container_name: bind9
    restart: always
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "127.0.0.1:953:953/tcp"
    volumes:
      - ./config/cdn/named.conf:/etc/bind/named.conf
      - ./config/cdn/db.cdn.local:/etc/bind/db.cdn.local
      - ./config/cdn/db.cdn2.local:/etc/bind/db.cdn2.local
      - ./cache:/var/cache/bind
      - ./log:/var/log/bind
      - /run/named:/run/named
    environment:
      - BIND9_USER=root
    cap_add:
      - NET_ADMIN
    networks:
      cdn_net:
        ipv4_address: 192.168.97.5

  load_balancer_1:
    image: nginx:latest
    container_name: load_balancer_1
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/nginx_lb1.conf:/etc/nginx/nginx.conf
    networks:
      cdn_net:
        ipv4_address: 192.168.97.6
    depends_on:
      - node1
      - node2

  load_balancer_2:
    image: nginx:latest
    container_name: load_balancer_2
    ports:
      - "8080:80"
    volumes:
      - ./config/nginx/nginx_lb2.conf:/etc/nginx/nginx.conf
    networks:
      cdn_net:
        ipv4_address: 192.168.97.7
    depends_on:
      - node3
      - node4

  node1:
    build: .
    container_name: node1
    networks:
      cdn_net:
        ipv4_address: 192.168.97.8
    volumes:
      - cache_data:/cache

  node2:
    build: .
    container_name: node2
    networks:
      cdn_net:
        ipv4_address: 192.168.97.9
    volumes:
      - cache_data:/cache

  node3:
    build: .
    container_name: node3
    networks:
      cdn_net:
        ipv4_address: 192.168.97.10
    volumes:
      - cache_data:/cache

  node4:
    build: .
    container_name: node4
    networks:
      cdn_net:
        ipv4_address: 192.168.97.11
    volumes:
      - cache_data:/cache

  client_ukraine:
    build: ./client
    container_name: client_ukraine
    networks:
      cdn_net:
        ipv4_address: 192.168.97.20
    depends_on:
      - bind9
    environment:
      - REGION=UA
      - DNS_SERVER=192.168.97.5

  client_europe:
    build: ./client
    container_name: client_europe
    networks:
      cdn_net:
        ipv4_address: 192.168.97.21
    depends_on:
      - bind9
    environment:
      - REGION=EU
      - DNS_SERVER=192.168.97.5

networks:
  cdn_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.97.0/24

volumes:
  cache_data:
    driver: local
