version: '3.8'

services:
  bind:
    image: sameersbn/bind
    container_name: bind
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    networks:
      - cdn_net
    volumes:
      - ./bind:/etc/bind

  load_balancer_1:
    image: nginx:latest
    container_name: load_balancer_1
    ports:
      - "8081:80"
    volumes:
      - ./nginx_lb1.conf:/etc/nginx/nginx.conf
    networks:
      - cdn_net
    depends_on:
      - node1
      - node2
      - node3
      - node4

  load_balancer_2:
    image: nginx:latest
    container_name: load_balancer_2
    ports:
      - "8082:80"
    volumes:
      - ./nginx_lb2.conf:/etc/nginx/nginx.conf
    networks:
      - cdn_net
    depends_on:
      - node1
      - node2
      - node3
      - node4

  node1:
    build: ./node
    container_name: node1
    networks:
      - cdn_net
    volumes:
      - cache_data:/cache

  node2:
    build: ./node
    container_name: node2
    networks:
      - cdn_net
    volumes:
      - cache_data:/cache

  node3:
    build: ./node
    container_name: node3
    networks:
      - cdn_net
    volumes:
      - cache_data:/cache

  node4:
    build: ./node
    container_name: node4
    networks:
      - cdn_net
    volumes:
      - cache_data:/cache

networks:
  cdn_net:
    driver: bridge

volumes:
  cache_data:
    driver: local
